---
- name: UPLOAD ROBONOMICS BINARY TO THE SERVER
  block:
    - name: "Use Robonomics binary from role files"
      copy: src=robonomics  dest=/usr/local/bin/robonomics mode='0755'
      when: CUSTOM_BINARY

    - name: "Use Robonomics binary from installer"
      # TODO: use uri or get_url
      shell: curl -sSf https://get.robonomics.network/install | sh
      when: not CUSTOM_BINARY
  tags: [ upload_binary ]


- name: REMOVE ROBONOMICS BINARY
  file: path=/usr/local/bin/robonomics state=absent
  tags: [ never, remove ]