---
- name: Remove relay db
  file:
    path: '{{ USER_PATH }}/.local/share/robonomics/polkadot/chains/{{ CHAIN_ID }}/db'
    state: absent 
  tags: [ never, remove_relaychain_db, remove_dbs ]

- name: Remove parachain db
  file:
    path: '{{ USER_PATH }}/.local/share/robonomics/chains/{{ PARACHAIN_NAME }}/db'
    state: absent
  tags: [ never, remove_parachain_db, remove_dbs ]