---
- name: Template robonomics.service
  template:
    src: robonomics-{{ NODE_TYPE }}.service.j2
    dest: /etc/systemd/system/{{ SERVICE_NAME }}.service
  notify: 
    - daemon-reload
    - robonomics-restart
  tags: [ set_service ]


- name: REMOVE SERVICE
  block:
    - name: "Delete service file"
      file:
        path: /etc/systemd/system/{{ SERVICE_NAME }}.service
        state: absent
  rescue: 
    - name: "Can't delete service file"
      debug: msg="There's no existing service file, run the next task"
  tags: [ never, remove ]