---
- name: "Create robonomics user"
  user:
    name: "{{ SERVICE_NAME }}"
    shell: /bin/bash
    # system: no       
    createhome: yes
    home: "{{ USER_PATH }}"
    state: present
  tags: [ create_user ]


- name: "Remove robonomics user"
  ansible.builtin.user:
    name: "{{ SERVICE_NAME }}"
    state: absent
    remove: yes
  tags: [ never, remove ]