---
- hosts: all
  user: root

  tasks:
    - name: Get df -h
      shell: df -h
      register: result

    - debug: msg={{ result.stdout_lines }}

    # TODO: add rsa keys from vars if it not added yet