---
- name: Create directory for test_keys.json if it doesn't exists
  file:
    path: data/uploads/common_nodes/{{ common_node_ip }}
    state: directory
    mode: "0755"

- name: Run handlers/generate_addresses.py
  script: handlers/generate_addresses.py -p data/uploads/common_nodes/{{ common_node_ip }}/test_accounts.json -c {{ config.common_nodes.test_accounts_count }}
  args:
    executable: "{{ playbook_dir }}/venv/bin/python3"

- set_fact:
    test_keys: "{{ lookup('file','data/uploads/common_nodes/{{ common_node_ip }}/test_accounts.json') | from_json }}"

- name: Set test_accounts var
  set_fact:
    all_test_keys: "{{ test_accounts | default([]) + test_keys['keys'] }}"
