---
- hosts: all
  user: root

  tasks:
  - name: xfs growfs on {{ growfs_dev }}
    community.general.filesystem:
      dev: "{{ growfs_dev }}"
      fstype: "{{ growfs_fstype }}"
      resizefs: yes
      