---
- name: UPLOAD RESTART SCRIPT
  block:
    - name: "Create directory for cron scripts"
      file:
        path: '{{ USER_PATH }}/cron'
        state: directory
        mode: 0755
        owner: '{{ SERVICE_NAME }}'
        group: '{{ SERVICE_NAME }}'

    - name: "Template robonomics-collator-restart.sh to user cron"
      template:
        src: robonomics-collator-restart.sh.j2
        dest: '{{ USER_PATH }}/cron/robonomics-collator-restart.sh'
        mode: 0755
        owner: '{{ SERVICE_NAME }}'
        group: '{{ SERVICE_NAME }}'
  tags: [ upload_restart_script ]

- name: "Add robonomics-collator-restart.sh to crontab"
  cron:
    name: "robonomics-collator-restart"
    minute: "*/5"
    job: "{{ USER_PATH }}/cron/robonomics-collator-restart.sh > /dev/null 2>&1"
  notify: crond-restart
  tags: [ set_cron_rules, start_service ]


- name: REMOVE CRON RULES
  block:
    - name: "Remove robonomics-collator-restart cron rule"
      cron:
        name: "robonomics-collator-restart"
        # env: yes
        state: absent
    # - shell: crontab -r
    #   notify: crond-restart
  rescue:
    - name: "There's no crontab for root"
      debug: msg="It's ok, go ahead"
  tags: [ never, remove , remove_cron_rules, stop_service ]