---
- name: UPLOAD RESTART SCRIPT
  block:
    - name: "Create directory for scripts"
      file:
        path: /home/{{ SERVICE_NAME }}/scripts
        state: directory
        mode: 0755

    - name: "Template robonomics-collator-restart.sh to user cron"
      template:
        src: robonomics-collator-restart.sh.j2
        dest: /home/{{ SERVICE_NAME }}/scripts/robonomics-collator-restart.sh
        mode: 0755
        owner: '{{ SERVICE_NAME }}'
        group: '{{ SERVICE_NAME }}'
  tags: [ upload_restart_script ]

- name: "Add robonomics-collator-restart.sh to crontab"
  ansible.builtin.cron:
    name: "robonomics-collator-restart"
    minute: "*/5"
    job: "/home/{{ SERVICE_NAME }}/scripts/robonomics-collator-restart.sh > /dev/null 2>&1"
  notify: crond-restart
  tags: [ set_cron_rules ]


- name: REMOVE CRON RULES
  block:
    - name: disable cron
      ansible.builtin.cron:
        name: "robonomics-collator-restart"
        # env: yes
        state: absent
    # - shell: crontab -r
    #   notify: crond-restart
  rescue:
    - name: "There's no crontab for root"
      debug: msg="It's ok, go ahead"
  tags: [ never, remove , remove_cron_rules ]