---
- name: UPLOAD SPEC TO THE SERVER
  block:
    - name: "Upload SPEC file to the server from role files"
      copy: src=spec-{{ PARACHAIN_NAME }}.json  dest={{ USER_PATH }}/spec.json mode='0755' owner={{ SERVICE_NAME }} group={{ SERVICE_NAME }}
  # rescue:
  #   - name: "No SPEC file for upload"
  #     debug: msg="Skip it"
  when: CUSTOM_SPEC
  tags: [ change_binary, upload_spec ]

- debug: msg="CUSTOM_SPEC={{ CUSTOM_SPEC }}"