---
###############################
########## NETWORK  ###########
###############################
- name: ==NETWORK== Create NETWORK a directory if it does not exist
  file:
    path: "{{ DATA_PATH }}/uploads/validators/{{ validator_ip }}/network"
    state: directory
    mode: "0755"

- name: ==NETWORK== Create secret_ed25519 for every node
  command: "{{ DATA_PATH }}/uploads/polkadot key generate-node-key --file {{ DATA_PATH }}/uploads/validators/{{ validator_ip }}/network/secret_ed25519"
  register: network_key
###############################
########## /NETWORK  ##########
############################### 


###############################
########## KEYSTORES  #########
############################### 
- name: ==KEYSTORE== Remove validator's keystore folder if it exists
  file: 
    path: "{{ DATA_PATH }}/uploads/validators/{{ validator_ip }}/keystore"
    state: absent
  
- name: ==KEYSTORE== Create validator's keystore folder
  file: 
    path: "{{ DATA_PATH }}/uploads/validators/{{ validator_ip }}/keystore"
    state: directory 
    mode: "0755"

- name: ==KEYSTORES== Create keystore keys with prefixes
  include_tasks: tasks/create_keystore_file.yml
  loop: "{{ lookup('dict', prefixes) }}"
  loop_control:
    loop_var: prefix

- name: Set keys for current node
  set_fact:
    nodes_session_keys: "{{ nodes_session_keys | default([]) + [session_keys] }}"
###############################
########## /KEYSTORES  ########
###############################