---
TELEMETRY_URL:  "wss://telemetry.polkadot.io/submit/ 0"
HAS_ADDITIONAL_VOLUME: no

# If RocksDB use 'db', if ParityDB use 'paritydb'
DB_DIRECTORY_NAME: "db"

PARACHAIN_NETWORK_KEY_PATH: "{{ BASE_PATH }}/chains/{{ PARACHAIN_NAME }}/network"