---
# - name: Template service file
#   template:
#     src: "{{ item }}.service.j2"
#     dest: /etc/systemd/system/{{ SERVICE_NAME }}.service
#   when: inventory_hostname in groups[item]
#   loop: [ bootnodes, collators, public_nodes ]
#   notify: 
#     - daemon-reload
#     - service-restart
#   tags: [ upload_service ]

- name: Template service file
  template:
    src: "service.j2"
    dest: /etc/systemd/system/{{ SERVICE_NAME }}.service
  when: inventory_hostname in groups[item]
  loop: [ bootnodes, collators, public_nodes ]
  notify: 
    - daemon-reload
    - service-restart
  tags: [ upload_service ]

- name: REMOVE {{ SERVICE_NAME }} SERVICE
  block:
    - name: "Delete service file"
      file:
        path: /etc/systemd/system/{{ SERVICE_NAME }}.service
        state: absent
  rescue: 
    - name: "Can't delete service file"
      debug: msg="There's no existing service file, run the next task"
  tags: [ never, remove ]