---
- name: daemon-reload
  shell: systemctl daemon-reload

- name: service-restart
  service:
    name: '{{ SERVICE_NAME }}'
    state: restarted

- name: crond-restart
  service:
    name: cron
    state: restarted