- name: Restart the Prometheus service
  service:
    name: prometheus
    state: restarted
  listen: prometheus_restart

- name: Reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload