---
- name: "Create {{ SERVICE_NAME }} user"
  user:
    name: "{{ SERVICE_NAME }}"
    shell: /bin/bash
    createhome: yes
    system: yes
    home: "{{ USER_PATH }}"
    state: present
  tags: [ never, init, add_validators ]

- name: "Change base path permissions"
  file:
    path: "{{ BASE_PATH }}"
    state: directory
    mode: 0755
    owner: "{{ SERVICE_NAME }}"
    group: "{{ SERVICE_NAME }}"
  tags: [ never, init, add_validators ]

# - block:
  # - name: Get additional volume name
  #   shell: ls /mnt/
  #   register: VOLUME_NAME

  # - debug: msg={{ VOLUME_NAME }}

  # - name: Create polkadot folder 
  #   file: 
  #     path: "{{ USER_PATH }}/.local/share"
  #     owner: "{{ SERVICE_NAME }}"
  #     group: "{{ SERVICE_NAME }}"
  #     mode: '0775'
  #     state: directory

  # - name: Create symbolic link 
  #   file:
  #     src: "/mnt/{{ VOLUME_NAME.stdout }}"
  #     dest: "{{ USER_PATH }}"
  #     owner: "{{ SERVICE_NAME }}"
  #     group: "{{ SERVICE_NAME }}"
  #     mode: '0775'
  #     state: link
  # tags: [never, init]


- name: "Remove {{ SERVICE_NAME }} user"
  ansible.builtin.user:
    name: "{{ SERVICE_NAME }}"
    state: absent
    remove: yes
  tags: [ never, remove ]